export const coupons = {
    SAVE10:{
        name:'SAVE10',
        discount:10
    },
    SAVE20:{
        name:'SAVE20',
        discount:20
    },
    VARUN:{
        name:'VARUN',
        discount:50
    },
    RITU:{
        name:'RITU',
        discount:50
    },
    KHUSHBOO:{
        name:'KHUSHBOO',
        discount:50
    }
}
